# Generated by Django 4.0.3 on 2022-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsName', models.CharField(max_length=100)),
                ('productsCategory', models.TextField()),
                ('productsQuantity', models.TextField()),
                ('productsPrice', models.TextField()),
            ],
        ),
    ]
