# Generated by Django 4.0.3 on 2022-03-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0002_addstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstock',
            name='productsName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addstock',
            name='productsPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addstock',
            name='productsQuantity',
            field=models.IntegerField(),
        ),
    ]
