# Generated by Django 4.0.3 on 2022-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0003_alter_addstock_productsname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='addstock',
            name='productsName',
            field=models.CharField(max_length=100),
        ),
    ]
