# Generated by Django 4.0.3 on 2022-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagement', '0004_delete_post_alter_addstock_productsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstock',
            name='productsCategory',
            field=models.CharField(max_length=20),
        ),
    ]
